server:
  port: 8080
  servlet:
    context-path: /api/

logging:
  level:
    org.springframework.web: error
    org.hibernate: error
    org.apache.http: error


spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true
  messages.basename: validation
  thymeleaf.cache: false
  messages:
    basename: messages
  jackson:
    date-format: yyyy-MM-dd

management:
  endpoints:
    web:
      exposure:
        include: "*"
cloudinary:
  cloud_name: sgrkale
  api_key: 423365436679876
  api_secret: lc9l1fKrtifRCquCezCUSbGOLTQ

jasypt:
  encryptor:
    password: ${APP_ENCRYPTION_PASSWORD}
    property:
      prefix: SGR(


---
spring:
  profiles: mysql
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/kirana_shop_db"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: SGR(46XouROSms9c5YhAYdON8g==)
    password: SGR(FJTGVA85VBjS9W2hWvIkMA==)
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
---
spring:
  profiles: postgres
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: com.mysql.jdbc.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.ProgressDialect
---
spring:
  profiles: errorlogs
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
        type: trace
    show-sql: true
  thymeleaf:
    cache: false

logging:
  level:
    com.sagar: error
    org.springframework.web: error
    org.hibernate: error
    org.apache.http: error
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
management:
  endpoints:
    web:
      exposure:
        include: "*"